# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Validate-URI
version:      0.01
version_from: lib/Data/Validate/URI.pm
installdirs:  site
requires:
    Data::Validate::Domain:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
